### ISSUE TITLE
"logml could not be estimated within maxiter"

### ISSUE THREAD

**Issue by lindeloev** [quentingronau/bridgesampling#14]
I compare two `brmsfit`s using `brms::bayes_factor` and 20.000 iterations. It restarted iterating three times, ending in the following error:

```
Error: Bridgesampling failed. Did you set 'save_all_pars' to TRUE when fitting your model?
In addition: Warning messages:
1: logml could not be estimated within maxiter, rerunning with adjusted starting value. 
Estimate might be more variable than usual. 
2: Infinite value in iterative scheme, returning NA.
 Try rerunning with more samples. 
3: logml could not be estimated within maxiter, rerunning with adjusted starting value. 
Estimate might be more variable than usual. 
```

I did set `save_all_pars = TRUE` in both models. What might be the problem here?
1. Does this mean that the evidence is very strong in favor of one of the models? If so, is there a way to know which one?
2. Should I try with *even more* iterations?
3. Or is this a model comparison that `bridgesampling` simply cannot navigate? 

I'm happy to share the `brmsfits` if that can be of any help.

The model is quite complicated. It took ~60 hours to get 1000 samples (from each of 6 parallel chains) and stan kept reaching a `treedepth` of 11, which was the upper limit I set. However, convergence is fine and the parameters estimated to good precision.

**Comment by lindeloev** [comment]
Update: I get the same warning(s) with `maxiter = 2*10^5`

**Comment by singmann** [comment]
Without a reproducible example, it is always quite difficult to provide extensive solution. However, here the problem seems quite clear. You need more posterior samples. As we write in our paper:

>  As a rule of thumb, we suggest that testing requires about an order of magnitude
more posterior samples than estimation.

So if you only have 6,000 posterior samples overall, you might have a lot more luck with 60,000 samples instead. The problem is not the number of iterations from `bridgesampling`, but the number of posterior samples you pass to `bridgesampling`.

From your description it seems clear that this would take a lot of time, and potentially also a lot of RAM, but I guess there is no other advise we could give. 

Also, please be aware that the priors in `brms` are not designed for Bayes factor based model selection so we currently do not recommend `brms` together with `bridgesampling`.

**Comment by lindeloev** [comment]
Thank you, @singmann, that's very helpful. I will try and add some more samples and see how it goes. Hopefully, it catches up before 60.000 samples! I have explicitly set all priors for the model to be normal or gamma. The exception is the Cholesky prior on random effects (``lkj(1)`). Could that pose a problem for `bridgesampling`?

**Comment by singmann** [comment]
It should not lead to problems in the estimation of the Bayes factors, they are probably just difficult to interpret or even meaningless. Priors for Bayes factors must be chosen specifically for this purpose. Priors that are good for estimation are usually not good for Bayes factors. For Bayes factors a good option would be some sort of default priors. To the best of my knowledge, such priors are not available in `brms`.

For Bayes factor specific priors see:
Ly, A., Verhagen, J., & Wagenmakers, E.-J. (2016). Harold Jeffreys’s default Bayes factor hypothesis tests: Explanation, extension, and application in psychology. Journal of Mathematical Psychology, 72(Supplement C), 19–32. https://doi.org/10.1016/j.jmp.2015.06.004
Rouder, J. N., Morey, R. D., Speckman, P. L., & Province, J. M. (2012). Default Bayes factors for ANOVA designs. Journal of Mathematical Psychology, 56(5), 356–374. https://doi.org/10.1016/j.jmp.2012.08.001

**Comment by singmann** [comment]
Without a reproducible example it is difficult to fix anything. 

In addition, changing the error to a warning and returnign `NA` will be difficult for us, as the following error comes from `brms:::bridge_sampler.brmsfit`: `Bridgesampling failed. Did you set 'save_all_pars' ...`  This means, Paul Buerkner will have to make this change. 

Nevertheless, I am back at working on the package. So if there is a reproducible example, I am happy to investigate the cause.

**Comment by paul-buerkner** [comment]
The GitHub version of brms should now show the actual error message of `bridge_sampler`. Is that what you meant @singmann?

**Comment by singmann** [comment]
I was referring to @bnicenboim's wish to return `NA` and emit a warning instead of throwing an error. But passing on the exact error message will probably help in getting some reproducible examples to make `bridgesampling` more robust.

**Comment by paul-buerkner** [comment]
When brms says that "bridgesampling failed" then `bridge_sampler` returned an error and brms just suppressed the actual error mesage (not anymore though). Accordingly, there is no reason to return NA (with a warning) in this case.

**Comment by singmann** [comment]
I can see that it makes some sense that we would return `NA` in such a case instead of you having to `tryCatch` that. We will do so, as soon as we get a reproducible example.

**Comment by singmann** [comment]
We just checked it again and we do not throw an `error` in case it `logml could not be estimated within maxiter`, only a `warning` and return `NA`. So this issue seems to be somehow related to how `brms` deals with `NA`s coming from `bridge_sampler`. But there also seems nothing for us to do at the moment. Unless someone has a different opinion we will close.

**Comment by wlandau** [comment]
> So if you only have 6,000 posterior samples overall, you might have a lot more luck with 60,000 samples instead. The problem is not the number of iterations from bridgesampling, but the number of posterior samples you pass to bridgesampling.

Number of samples, or number of *effective* samples? Is it just a matter of giving the `bridgesampling` package enough data, or is it something to do with sufficiently exploring the posterior? In the former case, would it be valid to just bootstrap more samples from the existing MCMC output?
