### ISSUE TITLE
Dynamic bounds

### ISSUE THREAD

**Issue by lindeloev** [quentingronau/bridgesampling#19]
Some of my parameters are bounded by another parameter to ensure order restriction. For example:

    cp_1 = dunif(0, 100)  # fixed bounds
    cp_2 = dunif(cp_1, 100)  # greater than cp_1

Currently `bridgesampling` takes a static vector of variable bounds. Is there a way to use it for situations like the above? Although `dunif` is the default prior, the user can specify others as well, e.g., `cp_2 = dnorm(50, 1/20^2) T(cp_1, )`.

**Comment by quentingronau** [comment]
You could try to use Stan and its ordered vector type in combination with `bridgesampling`. Alternatively, you could use any sampling software or custom sampler in combination with `bridgesampling` and implement the transformation and corresponding Jacobian adjustment of the (unnormalized) log posterior yourself ([this](https://mc-stan.org/docs/2_20/reference-manual/ordered-vector.html) part of the Stan reference manual might be of help). That is, you would need to provide `bridgesampling` with the already to the real line transformed samples and you would need to adjust your `log_posterior` function.

**Comment by lindeloev** [comment]
Great to hear that it is possible and thank you for pointing out how! It too big a mouthful for me right now, but I hope to revisit later. I may do a `stan` implementation in the future.
