### ISSUE TITLE
Link to vignette is broken

### ISSUE THREAD

**Issue by fdabl** [quentingronau/bridgesampling#2]
Hi Quentin,

this package looks super cool, nice work!

Note that the link to the vignette points to a file called "bridgesampling_example.html" which does not exist (there are only example_jags.html, example_stan.html, and stan_ttest.html). I suppose it is best to link to them separately.

Cheers,
Fabian

**Comment by quentingronau** [comment]
Hi Fabian,

Thanks a lot!
Great that you noticed this. I just adjusted the README.md file and the links should work now again.
Please let me know in case there is still an issue with the link.

Cheers,
Quentin
