### ISSUE TITLE
Stops knitting when used

### ISSUE THREAD

**Issue by utkuturk** [quentingronau/bridgesampling#25]
Hi,

Whenever I use bridge_sample in my code, I cannot knit my document. when the chunk that includes bridge_sample function, it tries to do it for 1-2 minutes, then just stops. No error message. When I run the code one by one, everything works as expected. 

Is there a way to save the output of this function similar to saving brmsfit's as a RDS. So that it does not take too much time every time and maybe enable me to knit?

**Comment by singmann** [comment]
sorry for the late reply, but any object created by `bridgesampling` can be saved in binary form via `save()` and loaded via `load()`. For example:

```r
bridge_result <- bridge_sampler(...)
save(bridge_result, file = "bridge_result.rda")
```

Load via:
```r
load("bridge_result.rda")
```
