### ISSUE TITLE
Error when parallelizing stan models

### ISSUE THREAD

**Issue by kabarigou** [quentingronau/bridgesampling#28]
Hello,

I am running five stan models in parallel using the **parallel** package (in order to do some Bayesian model averaging), and unfortunately, I ran to the already encountered error: 
`Error in .local(object, ...) : 
  the model object is not created or not valid`

For info, my R code is the following: 
```R
library(parallel)
samplingfunction<-function(x){
  if (x==1) res<-rstan::sampling(LCmodel,data=standata,chains=4,cores=4)
  else if (x==2) res<-rstan::sampling(RHmodel,data=standata,chains=4,cores=4)
  else if (x==3) res<-rstan::sampling(APCmodel,data=standata,chains=4,cores=4)
  else if (x==4) res<-rstan::sampling(CBDmodel,data=standata2,chains=4,cores=4)
  else if (x==5) res<-rstan::sampling(M6model,data=standata2,chains=4,cores=4)
}
cl <- makeCluster(20)
clusterExport(cl,c('LCmodel','RHmodel','APCmodel','CBDmodel','M6model','standata','standata2'))
system.time({out <- parLapply(cl, c(1:5),samplingfunction)})
```
Hence, I fit 5 models in parallel with 4 chains each using the 20 cores of my computer. If I fit one model at a time and use the function `bridge_sampler`, there is no problem. However, after parallelization above, if I call
`bridge1 <- bridge_sampler(out[[1]],silent = TRUE)` I get
`Error in .local(object, ...) : 
  the model object is not created or not valid`

For the moment, I use the "trick" of creating an empty model before calling the `bridge_sampler` function but is there not a more elegant solution ? 
For a simulation study, I will have to run the five stan models above on 1000 different datasets and I would like to avoid calling the **stan** function  `5000` times. 

Thanks for your help and congratulations to the authors for this already nice package !

**Comment by singmann** [comment]
I think this error message comes from `rstan` and not from us. I believe it means that for some reason the compiled model cannot be accessed. 

This also means there is nothing we can do about this form our end. `bridgesampling` requires a model object for which we can call the `rstan::log_prob()` function and for some reason you cannot do so for the ones using parallel. There might be a way to do so, but it is more of a `rstan` question. 

As an alternative, you can always rebuild the model in `R` and simply avoid using `rstan`, but this will only make sense in very simple cases as you will have to take care of the variable transformations as well. 

I will close this issue for now as I do not believe we can do anything about it.
