### ISSUE TITLE
Parallelize `bf()`

### ISSUE THREAD

**Issue by JeffreyRStevens** [quentingronau/bridgesampling#34]
Does the `bf()` function have a way to parallelize the computations across repetitions? Or should I run `bf()` repeatedly using external parallelization? Basically, I'm looking for any way to speed up processing for a very long processing time.

**Comment by quentingronau** [comment]
Hi Jeffrey,

The `bf` function does not, but the `bridge_sampler` function has. Once the log marginal likelihoods have been computed via `bridge_sampler`, using `bf` should be very quick.

Cheers,
Quentin

**Comment by JeffreyRStevens** [comment]
Many thanks for your reply, @quentingronau. That clarifies where the action is. When using the `bridge_sampler()` function, I see that I can specify the number of `cores` to parallelize the processing. I have a few questions, if you don't mind.
* Does the parallelization work between or within repetitions?
* How can I best speed up processing? Currently, if I run on 1 core, one of my models takes 14.6 minutes. Bumping up to 4 cores drops the time to 10.3 minutes and 8 cores is 9.7 minutes. So I'm not getting a huge benefit from many cores. Also, in watching my system resources, multiple cores are only used a relatively small part of that processing time (less than half). Are there any other ways to speed up processing besides increasing `cores`?

System specs: R version 4.2.2; bridgesampling version 1.1-2; Ubuntu 22.04.2
