### ISSUE TITLE
Some suggestions for the S3 generic functions

### ISSUE THREAD

**Issue by paul-buerkner** [quentingronau/bridgesampling#4]
Thanks for making **bridgesampling**! It seems to be a promising approach to making Bayes factors widely usable for more complex models. 

While incorporating **bridgesampling** into **brms**, I found a few things about the S3 generic that I feel could be improved:

1. The `bf` generic does not seem to have a `...` argument, which is unfortunate, given that we then cannot write methods for this generic with more than the three argument `x1`, `x2` and `log`. Further, it enforces to have a `log` argument and I am not sure whether we should always want one. I thus suggest redefinint the generic to

```R
bf <- function(x1, x2, ...)
```

2.  The `post_prob` generic forces us to have auxiliary arguments just as `model_names`. Just using

```R
post_prop <- function(x, ...)
```

should suffice I think.

3. More **brms** specific: The `bf` function is already defined in **brms** as a short form for `brmsformula`. I think it would be nice to also have a `bayes_factor` generic in **bridgesampling**, which is just used as an alias of `bf`. I also feel that `bayes_factor` is more consistent with the other names of the generic methods. Currently, I just define the `bayes_factor` generic in **brms** myself, but I think having it all in one package is actually preferable.

**Comment by singmann** [comment]
1. To avoid overflow/underflow log is necessary in the bf() method. Like in basically all PDFs in R. Adding a ... argument should be no problem. Do you have any specific ideas of what arguments to add? So far we hadn't added one because we did not see which additional arguments would be necessary.

2. In my view the problem with defining minimal S3 generics as you suggest is that it somewhat impedes the usage within RStudio (or similar IDEs), as the additional arguments do not appear when pressing tab. So one is then forced to remember their exact names (who does that?) or check the documentation (kind of annoying). Especially in cases like this where all methods need these arguments (at least the prior_prob one, but all our methods also use model_names), we therefore opted to write a more encompassing generic. I hope you find this convincing.

3. Good idea. We will adding bayes_factor() as alias for bf().

Thanks for your comments.

**Comment by paul-buerkner** [comment]
1. Your argument why to have `log` in the generic makes sense. For `brms` I use the `...` argument just to pass stuff to `bridge_sampler` (without being explicit about the names). Here is how the method looks like

```R
bayes_factor.brmsfit <- function(x1, x2, log = FALSE, ...) {
  match_response(list(x1, x2))
  bs1 <- bridge_sampler(x1, ...)
  bs2 <- bridge_sampler(x2, ...)
  bridgesampling::bf(bs1, bs2, log = log)
} 
```

2. You are right, I guess I am just a fan of minimal generics ;-) Not sure if `model_names` is general enough (for future methods in other packages) to be part of the generic, though. In `brms` I can make use of it, so both is fine for me.

3. Thanks!

**Comment by singmann** [comment]
Both points should be taken care of now (commit caf5570cb02a2cd33c8c507ace3a96c06b6a8860 and before). Can you test if this is what you need?
We are about to push a new version.

**Comment by paul-buerkner** [comment]
I do not see changes related to this issue in commt caf5570. Did you mean bc3a575?

If yes, I am not sure if the implementation of `bayes_factor()` is what I had in mind, since your function is not S3 generic.

**Comment by singmann** [comment]
I see, that makes sense. Can you check whether the changes in 3def02dbb05a23dc59454743894aaeedf247836f are more to your liking?

We now get:
```
> isS3stdGeneric(bayes_factor)
bayes_factor 
        TRUE 
```

**Comment by singmann** [comment]
see also bug fix in 7851c22ae398c87143b3debde1d14a164cbe067c

**Comment by paul-buerkner** [comment]
This looks perfect, thanks!

**Comment by singmann** [comment]
Wonderful. Then I am closing this issue. Please let us know if anything else comes up.

One more thing, that could be of interest. We have added the following warning to `?bridge_sampler` that mentions your package. This is just to ensure that people really think about their prior choices.

> Note that the results depend strongly on the parameter priors. Therefore, it is strongly advised to think carefully about the priors before calculating marginal likelihoods. For example, the prior choices implemented in \pkg{rstanarm} or \pkg{brms} might not be optimal from a testing point of view. We recommend to use priors that have been chosen from a testing and not a purely estimation perspective.
> 
> Also note that for testing, the number of posterior samples usually needs to be substantially larger than for estimation.

**Comment by paul-buerkner** [comment]
Thanks for letting me know. This sounds like a very important and useful warning to me!
