### ISSUE TITLE
Difference between bridgesampling and savage dickey BFs

### ISSUE THREAD

**Issue by paul-buerkner** [quentingronau/bridgesampling#5]
Today I played around a bit with bayes factors in brms and found the following example, where the bridgesampling and savage dickey BFs were somewhat different:

```R
library(brms)
data("sleepstudy", package = "lme4")

# compare BFs of random effects correlation
# use flat prior over [-1, 1]
# option 1:
fit <- brm(Reaction ~ Days + (Days|Subject), sleepstudy,
           sample_prior = "yes")
(hyp <- hypothesis(fit, "cor_Subject__Intercept__Days = 0", class = ""))
# BF01 = 2.61
plot(hyp)

# option 2:
fit1 <- brm(Reaction ~ Days + (Days||Subject), sleepstudy,
            save_all_pars = TRUE)
fit2 <- brm(Reaction ~ Days + (Days|Subject), sleepstudy,
            save_all_pars = TRUE)
bayes_factor(fit1, fit2)
# BF01 = 1.17
```

This is probably not a huge difference and not substantial when it comes to conclusions, but I still wonder if this is something worth investing in more detail.

**Comment by quentingronau** [comment]
Hi Paul,

Thanks for letting us know.
We are currently investigating this [here](http://discourse.mc-stan.org/t/question-about-lkj-normalizing-constant/2001).

Cheers,
Quentin

**Comment by paul-buerkner** [comment]
Thanks for looking into this!

**Comment by singmann** [comment]
The bug in Stan (particularly `StanHeaders`) was unfortunately not resolved in the latest updated on CRAN (see [here](http://discourse.mc-stan.org/t/question-about-lkj-normalizing-constant/2001/16?u=henrik_singmann)).

However, I found a temporary solution by replacing the problematic LKJ code in `StanHeaders` with the fixed version from the Stan github repository (it is unclear why this was not done in the latest release). This version appears to works:

```
install.packages("http://singmann.org/download/r/StanHeaders_2.17.2.tar.gz", repos = NULL)
library(brms)
data("sleepstudy", package = "lme4")
fit1 <- brm(Reaction ~ Days + (Days||Subject), sleepstudy,
            save_all_pars = TRUE)
fit2 <- brm(Reaction ~ Days + (Days|Subject), sleepstudy,
            save_all_pars = TRUE)
bayes_factor(fit1, fit2)
# BF01 = 2.58258
```

We will update again, once this is resolved in the CRAN version of Stan.

**Comment by paul-buerkner** [comment]
Thanks for the update! I believe they did not put it into the last release to make sure the last version not requiring C++11 is definitely stable, since the next Stan version (2.18) will require C++11. Anyway, it is good to know that we have a workaround for the problem now!

**Comment by singmann** [comment]
Another version of `StanHeaders` has appeared on CRAN (2.17.2) and this still [does not solve the problem](http://discourse.mc-stan.org/t/question-about-lkj-normalizing-constant/2001/20?u=henrik_singmann).

However, Ben Goodrich has provided another workaround that works (while we still wait for the fix in 2.18):

```
download.file("https://raw.githubusercontent.com/stan-dev/math/develop/stan/math/prim/mat/prob/lkj_corr_lpdf.hpp", 
destfile = system.file("include", "stan", "math", "prim", "mat", "prob", "lkj_corr_lpdf.hpp", package = "StanHeaders"))
```

**Comment by paul-buerkner** [comment]
Thanks, I will try that out!

**Comment by bnicenboim** [comment]
Hi, I just wanted to update you that it works now.
`hyp = 2.45` and `bayes_factor(fit1, fit2) = 2.5` with rstan_2.18.2

**Comment by quentingronau** [comment]
Great, thanks for letting us know!
