### ISSUE TITLE
Error when using on saved models

### ISSUE THREAD

**Issue by fdabl** [quentingronau/bridgesampling#7]
Hi,

I get the following error when I use bridge_sampler on a model that I saved to a .RDS file.

```r
fit <- readRDS('fitted-model.RDS')
bridge_sampler(fit)

Error in .local(object, ...) : 
  the model object is not created or not valid
```

Say, as a toy example, for this model.
```r
m <- '
data {
  int n;
  real y[n];
}

parameters {
  real mu;
}

model {
  target += normal_lpdf(mu | 0, 5);
  target += normal_lpdf(y | mu, 1);
}'

set.seed(1774)
dat <- list('y' = rnorm(100, 10, 1), 'n' = 100)
fit <- stan(model_code = m, data = dat)
# bridge_sampler(fit) works fine
saveRDS(fit, 'fitted-model.RDS')
```

Do you know what the issue might be? Thanks for any help!

**Comment by singmann** [comment]
We are aware of this issue and it is a general problem. It is a problem with `rstan` that is unrelated to the `bridgesampling` package. For some weird reason, you cannot use objects saved in a previous R session for sampling in a different session. (There is the hope that this will change if `rstan` version 3 comes out eventually, but who knows.)

The easiest solution is to create a new empty model in the new session (i.e., `stan(..., chains = 0)`) and pass this as the `stanfit_model` object. The object fitted in the other session still needs to be the `samples` argument. For example:

```
load('fitted-model.RDS')
new_mod <- stan(model_code = m, data = dat, chains = 0)
bridgesampler(fit, new_mod)
```

Funnily enough, if `rstan_options(auto_write = TRUE)` in the first session, you do not need to recompile the model in the second. But you still have to create the new model object. 

Let us know, if this does not work.

**Comment by singmann** [comment]
I guess this solves it. I will therefore close this issue.

**Comment by lsolomyak** [comment]
I've been having the same issue but the solution of creating an empty model has no longer been working. Rather than getting an error i get no output. Am i doing something wrong? Or are there any alternative solutions? 
`new_mod <- rstan::stan("Memorystan",dataList1,chains=0)
 bridgesampling::bridge_sampler(fit,new_mod)`
